apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZXBvcmFiaTAxLmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJaRzlqYTJWeVkzSmxaRHBPWldWc1lXMUFNalEzIgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
